# Generated by Django 2.2.8 on 2020-05-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('token', models.CharField(max_length=45)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Fechas_especiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.IntegerField(choices=[(1, 'Feriados'), (2, 'Vacaciones'), (3, 'Otros')])),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('codigo', models.CharField(default=0, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.DateField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('tipo', models.IntegerField(choices=[(1, 'Otoño'), (2, 'Primavera')])),
                ('estado', models.IntegerField(choices=[(1, 'Terminado'), (2, 'En ejecucion'), (3, 'Por comenzar')])),
            ],
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Semestre', models.IntegerField(choices=[(5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno'), (10, 'Decimo')])),
                ('id_ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ramo')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('curso_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('profe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='ramo_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ramo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Semestre'),
        ),
        migrations.CreateModel(
            name='Calendario_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Calendario')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('id_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Semestre')),
            ],
        ),
    ]
